### ISSUE TITLE
Shall we provide links to the research project repository on the site?

### ISSUE THREAD

**Issue by 0bserver07** [AI-ON/ai-on.org#5]
I believe It would make things very helpful and easier to start if each research author can provide a repository link on the Project Details page.

For example on here this project: [Social media botnet detection and analysis](http://ai-on.org/projects/social-media-bot-detection.html) to provide the [repo's link](https://github.com/shawnwanderson/social-media-bot-detection).

In regards to the **format** of these repositories. Using @shawnwanderson's repo as a skeleton, I created this [AI-ON-Sample Project](https://github.com/0bserver07/ai-on-sample-project/).

Please feel free to give any suggestions you have (grammar mistakes, language), since I just wrote this sample now in few minutes.

PS: I will include this repo on the [AI-ON Org](https://github.com/AI-ON) and this repo's readme, if it sounds like a good idea, cc: @fchollet.

**Comment by fchollet** [comment]
In short, yes we should. In general we should provide as many resources as possible on the project pages so newcomers can get started quickly.

**Comment by 0bserver07** [comment]
Sounds good, I will:
1. Add the repo example to the AI-On.Org description and Repos.
2. Do a pull-request to add the links to the existing research project repos that I can find.

**Comment by fchollet** [comment]
SGTM. Thanks!
